// SystemPhysics Protocol v1 — server-to-agent configuration push.
// Used to deliver generated OTEL Collector YAML from Core to the Framework.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: spp/v1/config.proto

package sppv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OtelYaml      []byte                 `protobuf:"bytes,1,opt,name=otel_yaml,json=otelYaml,proto3" json:"otel_yaml,omitempty"`
	ConfigId      string                 `protobuf:"bytes,2,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	HostId        string                 `protobuf:"bytes,3,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	PlanId        string                 `protobuf:"bytes,4,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPush) Reset() {
	*x = ConfigPush{}
	mi := &file_spp_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPush) ProtoMessage() {}

func (x *ConfigPush) ProtoReflect() protoreflect.Message {
	mi := &file_spp_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPush.ProtoReflect.Descriptor instead.
func (*ConfigPush) Descriptor() ([]byte, []int) {
	return file_spp_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigPush) GetOtelYaml() []byte {
	if x != nil {
		return x.OtelYaml
	}
	return nil
}

func (x *ConfigPush) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

func (x *ConfigPush) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *ConfigPush) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

var File_spp_v1_config_proto protoreflect.FileDescriptor

const file_spp_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x13spp/v1/config.proto\x12\x06spp.v1\"x\n" +
	"\n" +
	"ConfigPush\x12\x1b\n" +
	"\totel_yaml\x18\x01 \x01(\fR\botelYaml\x12\x1b\n" +
	"\tconfig_id\x18\x02 \x01(\tR\bconfigId\x12\x17\n" +
	"\ahost_id\x18\x03 \x01(\tR\x06hostId\x12\x17\n" +
	"\aplan_id\x18\x04 \x01(\tR\x06planIdB/Z-github.com/entropyops/entropyops-v2/pkg/sppv1b\x06proto3"

var (
	file_spp_v1_config_proto_rawDescOnce sync.Once
	file_spp_v1_config_proto_rawDescData []byte
)

func file_spp_v1_config_proto_rawDescGZIP() []byte {
	file_spp_v1_config_proto_rawDescOnce.Do(func() {
		file_spp_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spp_v1_config_proto_rawDesc), len(file_spp_v1_config_proto_rawDesc)))
	})
	return file_spp_v1_config_proto_rawDescData
}

var file_spp_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_spp_v1_config_proto_goTypes = []any{
	(*ConfigPush)(nil), // 0: spp.v1.ConfigPush
}
var file_spp_v1_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spp_v1_config_proto_init() }
func file_spp_v1_config_proto_init() {
	if File_spp_v1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spp_v1_config_proto_rawDesc), len(file_spp_v1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spp_v1_config_proto_goTypes,
		DependencyIndexes: file_spp_v1_config_proto_depIdxs,
		MessageInfos:      file_spp_v1_config_proto_msgTypes,
	}.Build()
	File_spp_v1_config_proto = out.File
	file_spp_v1_config_proto_goTypes = nil
	file_spp_v1_config_proto_depIdxs = nil
}
