// SystemPhysics Protocol v1 — host fingerprint messages.
// Maps to fingerprint.HostFingerprint in the Go codebase.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: spp/v1/fingerprint.proto

package sppv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Fingerprint struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Os               string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch             string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Kernel           string                 `protobuf:"bytes,3,opt,name=kernel,proto3" json:"kernel,omitempty"`
	CloudProvider    string                 `protobuf:"bytes,4,opt,name=cloud_provider,json=cloudProvider,proto3" json:"cloud_provider,omitempty"`
	Hostname         string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	ContainerRuntime string                 `protobuf:"bytes,6,opt,name=container_runtime,json=containerRuntime,proto3" json:"container_runtime,omitempty"`
	Platform         string                 `protobuf:"bytes,7,opt,name=platform,proto3" json:"platform,omitempty"`
	LparInfo         *LPARInfo              `protobuf:"bytes,8,opt,name=lpar_info,json=lparInfo,proto3" json:"lpar_info,omitempty"`
	SmfTypes         []int32                `protobuf:"varint,9,rep,packed,name=smf_types,json=smfTypes,proto3" json:"smf_types,omitempty"`
	ActiveSubsystems []string               `protobuf:"bytes,10,rep,name=active_subsystems,json=activeSubsystems,proto3" json:"active_subsystems,omitempty"`
	MqManagers       []string               `protobuf:"bytes,11,rep,name=mq_managers,json=mqManagers,proto3" json:"mq_managers,omitempty"`
	IndustrialProtos []string               `protobuf:"bytes,12,rep,name=industrial_protos,json=industrialProtos,proto3" json:"industrial_protos,omitempty"`
	LegacyDetected   []*LegacyDetection     `protobuf:"bytes,13,rep,name=legacy_detected,json=legacyDetected,proto3" json:"legacy_detected,omitempty"`
	DetectedSoftware []*DetectedSoftware    `protobuf:"bytes,14,rep,name=detected_software,json=detectedSoftware,proto3" json:"detected_software,omitempty"`
	DetectedAgents   []*DetectedAgent       `protobuf:"bytes,15,rep,name=detected_agents,json=detectedAgents,proto3" json:"detected_agents,omitempty"`
	OpenPorts        []int32                `protobuf:"varint,16,rep,packed,name=open_ports,json=openPorts,proto3" json:"open_ports,omitempty"`
	Processes        []*ProcessInfo         `protobuf:"bytes,17,rep,name=processes,proto3" json:"processes,omitempty"`
	FingerprintId    string                 `protobuf:"bytes,18,opt,name=fingerprint_id,json=fingerprintId,proto3" json:"fingerprint_id,omitempty"`
	CollectedAt      *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	DurationNs       int64                  `protobuf:"varint,20,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
	Confidence       float64                `protobuf:"fixed64,21,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Fingerprint) Reset() {
	*x = Fingerprint{}
	mi := &file_spp_v1_fingerprint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fingerprint) ProtoMessage() {}

func (x *Fingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_spp_v1_fingerprint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fingerprint.ProtoReflect.Descriptor instead.
func (*Fingerprint) Descriptor() ([]byte, []int) {
	return file_spp_v1_fingerprint_proto_rawDescGZIP(), []int{0}
}

func (x *Fingerprint) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Fingerprint) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Fingerprint) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *Fingerprint) GetCloudProvider() string {
	if x != nil {
		return x.CloudProvider
	}
	return ""
}

func (x *Fingerprint) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Fingerprint) GetContainerRuntime() string {
	if x != nil {
		return x.ContainerRuntime
	}
	return ""
}

func (x *Fingerprint) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Fingerprint) GetLparInfo() *LPARInfo {
	if x != nil {
		return x.LparInfo
	}
	return nil
}

func (x *Fingerprint) GetSmfTypes() []int32 {
	if x != nil {
		return x.SmfTypes
	}
	return nil
}

func (x *Fingerprint) GetActiveSubsystems() []string {
	if x != nil {
		return x.ActiveSubsystems
	}
	return nil
}

func (x *Fingerprint) GetMqManagers() []string {
	if x != nil {
		return x.MqManagers
	}
	return nil
}

func (x *Fingerprint) GetIndustrialProtos() []string {
	if x != nil {
		return x.IndustrialProtos
	}
	return nil
}

func (x *Fingerprint) GetLegacyDetected() []*LegacyDetection {
	if x != nil {
		return x.LegacyDetected
	}
	return nil
}

func (x *Fingerprint) GetDetectedSoftware() []*DetectedSoftware {
	if x != nil {
		return x.DetectedSoftware
	}
	return nil
}

func (x *Fingerprint) GetDetectedAgents() []*DetectedAgent {
	if x != nil {
		return x.DetectedAgents
	}
	return nil
}

func (x *Fingerprint) GetOpenPorts() []int32 {
	if x != nil {
		return x.OpenPorts
	}
	return nil
}

func (x *Fingerprint) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *Fingerprint) GetFingerprintId() string {
	if x != nil {
		return x.FingerprintId
	}
	return ""
}

func (x *Fingerprint) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

func (x *Fingerprint) GetDurationNs() int64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

func (x *Fingerprint) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type LPARInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	SysplexId     string                 `protobuf:"bytes,3,opt,name=sysplex_id,json=sysplexId,proto3" json:"sysplex_id,omitempty"`
	CpcSerial     string                 `protobuf:"bytes,4,opt,name=cpc_serial,json=cpcSerial,proto3" json:"cpc_serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LPARInfo) Reset() {
	*x = LPARInfo{}
	mi := &file_spp_v1_fingerprint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LPARInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPARInfo) ProtoMessage() {}

func (x *LPARInfo) ProtoReflect() protoreflect.Message {
	mi := &file_spp_v1_fingerprint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPARInfo.ProtoReflect.Descriptor instead.
func (*LPARInfo) Descriptor() ([]byte, []int) {
	return file_spp_v1_fingerprint_proto_rawDescGZIP(), []int{1}
}

func (x *LPARInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LPARInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LPARInfo) GetSysplexId() string {
	if x != nil {
		return x.SysplexId
	}
	return ""
}

func (x *LPARInfo) GetCpcSerial() string {
	if x != nil {
		return x.CpcSerial
	}
	return ""
}

type LegacyDetection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LegacyDetection) Reset() {
	*x = LegacyDetection{}
	mi := &file_spp_v1_fingerprint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LegacyDetection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LegacyDetection) ProtoMessage() {}

func (x *LegacyDetection) ProtoReflect() protoreflect.Message {
	mi := &file_spp_v1_fingerprint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LegacyDetection.ProtoReflect.Descriptor instead.
func (*LegacyDetection) Descriptor() ([]byte, []int) {
	return file_spp_v1_fingerprint_proto_rawDescGZIP(), []int{2}
}

func (x *LegacyDetection) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LegacyDetection) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *LegacyDetection) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type DetectedSoftware struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName      string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Category         string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	MatchedProcesses []string               `protobuf:"bytes,4,rep,name=matched_processes,json=matchedProcesses,proto3" json:"matched_processes,omitempty"`
	MatchedPorts     []int32                `protobuf:"varint,5,rep,packed,name=matched_ports,json=matchedPorts,proto3" json:"matched_ports,omitempty"`
	MatchedConfigs   []string               `protobuf:"bytes,6,rep,name=matched_configs,json=matchedConfigs,proto3" json:"matched_configs,omitempty"`
	Confidence       float64                `protobuf:"fixed64,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Layer            string                 `protobuf:"bytes,8,opt,name=layer,proto3" json:"layer,omitempty"`
	CollectStrategy  string                 `protobuf:"bytes,9,opt,name=collect_strategy,json=collectStrategy,proto3" json:"collect_strategy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DetectedSoftware) Reset() {
	*x = DetectedSoftware{}
	mi := &file_spp_v1_fingerprint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectedSoftware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectedSoftware) ProtoMessage() {}

func (x *DetectedSoftware) ProtoReflect() protoreflect.Message {
	mi := &file_spp_v1_fingerprint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectedSoftware.ProtoReflect.Descriptor instead.
func (*DetectedSoftware) Descriptor() ([]byte, []int) {
	return file_spp_v1_fingerprint_proto_rawDescGZIP(), []int{3}
}

func (x *DetectedSoftware) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DetectedSoftware) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *DetectedSoftware) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *DetectedSoftware) GetMatchedProcesses() []string {
	if x != nil {
		return x.MatchedProcesses
	}
	return nil
}

func (x *DetectedSoftware) GetMatchedPorts() []int32 {
	if x != nil {
		return x.MatchedPorts
	}
	return nil
}

func (x *DetectedSoftware) GetMatchedConfigs() []string {
	if x != nil {
		return x.MatchedConfigs
	}
	return nil
}

func (x *DetectedSoftware) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DetectedSoftware) GetLayer() string {
	if x != nil {
		return x.Layer
	}
	return ""
}

func (x *DetectedSoftware) GetCollectStrategy() string {
	if x != nil {
		return x.CollectStrategy
	}
	return ""
}

type DetectedAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Cmdline       string                 `protobuf:"bytes,3,opt,name=cmdline,proto3" json:"cmdline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectedAgent) Reset() {
	*x = DetectedAgent{}
	mi := &file_spp_v1_fingerprint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectedAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectedAgent) ProtoMessage() {}

func (x *DetectedAgent) ProtoReflect() protoreflect.Message {
	mi := &file_spp_v1_fingerprint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectedAgent.ProtoReflect.Descriptor instead.
func (*DetectedAgent) Descriptor() ([]byte, []int) {
	return file_spp_v1_fingerprint_proto_rawDescGZIP(), []int{4}
}

func (x *DetectedAgent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DetectedAgent) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *DetectedAgent) GetCmdline() string {
	if x != nil {
		return x.Cmdline
	}
	return ""
}

type ProcessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cmdline       string                 `protobuf:"bytes,3,opt,name=cmdline,proto3" json:"cmdline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_spp_v1_fingerprint_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_spp_v1_fingerprint_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_spp_v1_fingerprint_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessInfo) GetCmdline() string {
	if x != nil {
		return x.Cmdline
	}
	return ""
}

var File_spp_v1_fingerprint_proto protoreflect.FileDescriptor

const file_spp_v1_fingerprint_proto_rawDesc = "" +
	"\n" +
	"\x18spp/v1/fingerprint.proto\x12\x06spp.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xde\x06\n" +
	"\vFingerprint\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x16\n" +
	"\x06kernel\x18\x03 \x01(\tR\x06kernel\x12%\n" +
	"\x0ecloud_provider\x18\x04 \x01(\tR\rcloudProvider\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\x12+\n" +
	"\x11container_runtime\x18\x06 \x01(\tR\x10containerRuntime\x12\x1a\n" +
	"\bplatform\x18\a \x01(\tR\bplatform\x12-\n" +
	"\tlpar_info\x18\b \x01(\v2\x10.spp.v1.LPARInfoR\blparInfo\x12\x1b\n" +
	"\tsmf_types\x18\t \x03(\x05R\bsmfTypes\x12+\n" +
	"\x11active_subsystems\x18\n" +
	" \x03(\tR\x10activeSubsystems\x12\x1f\n" +
	"\vmq_managers\x18\v \x03(\tR\n" +
	"mqManagers\x12+\n" +
	"\x11industrial_protos\x18\f \x03(\tR\x10industrialProtos\x12@\n" +
	"\x0flegacy_detected\x18\r \x03(\v2\x17.spp.v1.LegacyDetectionR\x0elegacyDetected\x12E\n" +
	"\x11detected_software\x18\x0e \x03(\v2\x18.spp.v1.DetectedSoftwareR\x10detectedSoftware\x12>\n" +
	"\x0fdetected_agents\x18\x0f \x03(\v2\x15.spp.v1.DetectedAgentR\x0edetectedAgents\x12\x1d\n" +
	"\n" +
	"open_ports\x18\x10 \x03(\x05R\topenPorts\x121\n" +
	"\tprocesses\x18\x11 \x03(\v2\x13.spp.v1.ProcessInfoR\tprocesses\x12%\n" +
	"\x0efingerprint_id\x18\x12 \x01(\tR\rfingerprintId\x12=\n" +
	"\fcollected_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\x12\x1f\n" +
	"\vduration_ns\x18\x14 \x01(\x03R\n" +
	"durationNs\x12\x1e\n" +
	"\n" +
	"confidence\x18\x15 \x01(\x01R\n" +
	"confidence\"p\n" +
	"\bLPARInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"sysplex_id\x18\x03 \x01(\tR\tsysplexId\x12\x1d\n" +
	"\n" +
	"cpc_serial\x18\x04 \x01(\tR\tcpcSerial\"\xc5\x01\n" +
	"\x0fLegacyDetection\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12>\n" +
	"\adetails\x18\x03 \x03(\v2$.spp.v1.LegacyDetection.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc1\x02\n" +
	"\x10DetectedSoftware\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12+\n" +
	"\x11matched_processes\x18\x04 \x03(\tR\x10matchedProcesses\x12#\n" +
	"\rmatched_ports\x18\x05 \x03(\x05R\fmatchedPorts\x12'\n" +
	"\x0fmatched_configs\x18\x06 \x03(\tR\x0ematchedConfigs\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x01R\n" +
	"confidence\x12\x14\n" +
	"\x05layer\x18\b \x01(\tR\x05layer\x12)\n" +
	"\x10collect_strategy\x18\t \x01(\tR\x0fcollectStrategy\"O\n" +
	"\rDetectedAgent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x18\n" +
	"\acmdline\x18\x03 \x01(\tR\acmdline\"M\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acmdline\x18\x03 \x01(\tR\acmdlineB/Z-github.com/entropyops/entropyops-v2/pkg/sppv1b\x06proto3"

var (
	file_spp_v1_fingerprint_proto_rawDescOnce sync.Once
	file_spp_v1_fingerprint_proto_rawDescData []byte
)

func file_spp_v1_fingerprint_proto_rawDescGZIP() []byte {
	file_spp_v1_fingerprint_proto_rawDescOnce.Do(func() {
		file_spp_v1_fingerprint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spp_v1_fingerprint_proto_rawDesc), len(file_spp_v1_fingerprint_proto_rawDesc)))
	})
	return file_spp_v1_fingerprint_proto_rawDescData
}

var file_spp_v1_fingerprint_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_spp_v1_fingerprint_proto_goTypes = []any{
	(*Fingerprint)(nil),           // 0: spp.v1.Fingerprint
	(*LPARInfo)(nil),              // 1: spp.v1.LPARInfo
	(*LegacyDetection)(nil),       // 2: spp.v1.LegacyDetection
	(*DetectedSoftware)(nil),      // 3: spp.v1.DetectedSoftware
	(*DetectedAgent)(nil),         // 4: spp.v1.DetectedAgent
	(*ProcessInfo)(nil),           // 5: spp.v1.ProcessInfo
	nil,                           // 6: spp.v1.LegacyDetection.DetailsEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_spp_v1_fingerprint_proto_depIdxs = []int32{
	1, // 0: spp.v1.Fingerprint.lpar_info:type_name -> spp.v1.LPARInfo
	2, // 1: spp.v1.Fingerprint.legacy_detected:type_name -> spp.v1.LegacyDetection
	3, // 2: spp.v1.Fingerprint.detected_software:type_name -> spp.v1.DetectedSoftware
	4, // 3: spp.v1.Fingerprint.detected_agents:type_name -> spp.v1.DetectedAgent
	5, // 4: spp.v1.Fingerprint.processes:type_name -> spp.v1.ProcessInfo
	7, // 5: spp.v1.Fingerprint.collected_at:type_name -> google.protobuf.Timestamp
	6, // 6: spp.v1.LegacyDetection.details:type_name -> spp.v1.LegacyDetection.DetailsEntry
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_spp_v1_fingerprint_proto_init() }
func file_spp_v1_fingerprint_proto_init() {
	if File_spp_v1_fingerprint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spp_v1_fingerprint_proto_rawDesc), len(file_spp_v1_fingerprint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spp_v1_fingerprint_proto_goTypes,
		DependencyIndexes: file_spp_v1_fingerprint_proto_depIdxs,
		MessageInfos:      file_spp_v1_fingerprint_proto_msgTypes,
	}.Build()
	File_spp_v1_fingerprint_proto = out.File
	file_spp_v1_fingerprint_proto_goTypes = nil
	file_spp_v1_fingerprint_proto_depIdxs = nil
}
