// SystemPhysics Protocol v1 — structured log messages.
// Maps 1:1 to storage.LogRecord in the Go codebase.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: spp/v1/logs.proto

package sppv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*LogRecord           `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBatch) Reset() {
	*x = LogBatch{}
	mi := &file_spp_v1_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatch) ProtoMessage() {}

func (x *LogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_spp_v1_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatch.ProtoReflect.Descriptor instead.
func (*LogBatch) Descriptor() ([]byte, []int) {
	return file_spp_v1_logs_proto_rawDescGZIP(), []int{0}
}

func (x *LogBatch) GetLogs() []*LogRecord {
	if x != nil {
		return x.Logs
	}
	return nil
}

type LogRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TraceId        string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId         string                 `protobuf:"bytes,4,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	ServiceName    string                 `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	SeverityText   string                 `protobuf:"bytes,6,opt,name=severity_text,json=severityText,proto3" json:"severity_text,omitempty"`
	SeverityNumber int32                  `protobuf:"varint,7,opt,name=severity_number,json=severityNumber,proto3" json:"severity_number,omitempty"`
	Body           string                 `protobuf:"bytes,8,opt,name=body,proto3" json:"body,omitempty"`
	Attributes     map[string]string      `protobuf:"bytes,9,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceAttrs  map[string]string      `protobuf:"bytes,10,rep,name=resource_attrs,json=resourceAttrs,proto3" json:"resource_attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	mi := &file_spp_v1_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_spp_v1_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_spp_v1_logs_proto_rawDescGZIP(), []int{1}
}

func (x *LogRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogRecord) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *LogRecord) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *LogRecord) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *LogRecord) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *LogRecord) GetSeverityText() string {
	if x != nil {
		return x.SeverityText
	}
	return ""
}

func (x *LogRecord) GetSeverityNumber() int32 {
	if x != nil {
		return x.SeverityNumber
	}
	return 0
}

func (x *LogRecord) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *LogRecord) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *LogRecord) GetResourceAttrs() map[string]string {
	if x != nil {
		return x.ResourceAttrs
	}
	return nil
}

var File_spp_v1_logs_proto protoreflect.FileDescriptor

const file_spp_v1_logs_proto_rawDesc = "" +
	"\n" +
	"\x11spp/v1/logs.proto\x12\x06spp.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"1\n" +
	"\bLogBatch\x12%\n" +
	"\x04logs\x18\x01 \x03(\v2\x11.spp.v1.LogRecordR\x04logs\"\xac\x04\n" +
	"\tLogRecord\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x04 \x01(\tR\x06spanId\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\x12#\n" +
	"\rseverity_text\x18\x06 \x01(\tR\fseverityText\x12'\n" +
	"\x0fseverity_number\x18\a \x01(\x05R\x0eseverityNumber\x12\x12\n" +
	"\x04body\x18\b \x01(\tR\x04body\x12A\n" +
	"\n" +
	"attributes\x18\t \x03(\v2!.spp.v1.LogRecord.AttributesEntryR\n" +
	"attributes\x12K\n" +
	"\x0eresource_attrs\x18\n" +
	" \x03(\v2$.spp.v1.LogRecord.ResourceAttrsEntryR\rresourceAttrs\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12ResourceAttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B/Z-github.com/entropyops/entropyops-v2/pkg/sppv1b\x06proto3"

var (
	file_spp_v1_logs_proto_rawDescOnce sync.Once
	file_spp_v1_logs_proto_rawDescData []byte
)

func file_spp_v1_logs_proto_rawDescGZIP() []byte {
	file_spp_v1_logs_proto_rawDescOnce.Do(func() {
		file_spp_v1_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spp_v1_logs_proto_rawDesc), len(file_spp_v1_logs_proto_rawDesc)))
	})
	return file_spp_v1_logs_proto_rawDescData
}

var file_spp_v1_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_spp_v1_logs_proto_goTypes = []any{
	(*LogBatch)(nil),              // 0: spp.v1.LogBatch
	(*LogRecord)(nil),             // 1: spp.v1.LogRecord
	nil,                           // 2: spp.v1.LogRecord.AttributesEntry
	nil,                           // 3: spp.v1.LogRecord.ResourceAttrsEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_spp_v1_logs_proto_depIdxs = []int32{
	1, // 0: spp.v1.LogBatch.logs:type_name -> spp.v1.LogRecord
	4, // 1: spp.v1.LogRecord.timestamp:type_name -> google.protobuf.Timestamp
	2, // 2: spp.v1.LogRecord.attributes:type_name -> spp.v1.LogRecord.AttributesEntry
	3, // 3: spp.v1.LogRecord.resource_attrs:type_name -> spp.v1.LogRecord.ResourceAttrsEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_spp_v1_logs_proto_init() }
func file_spp_v1_logs_proto_init() {
	if File_spp_v1_logs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spp_v1_logs_proto_rawDesc), len(file_spp_v1_logs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spp_v1_logs_proto_goTypes,
		DependencyIndexes: file_spp_v1_logs_proto_depIdxs,
		MessageInfos:      file_spp_v1_logs_proto_msgTypes,
	}.Build()
	File_spp_v1_logs_proto = out.File
	file_spp_v1_logs_proto_goTypes = nil
	file_spp_v1_logs_proto_depIdxs = nil
}
