// SystemPhysics Protocol v1 — metric messages.
// Maps 1:1 to storage.Metric in the Go codebase.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: spp/v1/metrics.proto

package sppv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricBatch) Reset() {
	*x = MetricBatch{}
	mi := &file_spp_v1_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricBatch) ProtoMessage() {}

func (x *MetricBatch) ProtoReflect() protoreflect.Message {
	mi := &file_spp_v1_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricBatch.ProtoReflect.Descriptor instead.
func (*MetricBatch) Descriptor() ([]byte, []int) {
	return file_spp_v1_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *MetricBatch) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	MetricName    string                 `protobuf:"bytes,3,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	MetricType    string                 `protobuf:"bytes,4,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"` // gauge, counter, histogram
	Value         float64                `protobuf:"fixed64,5,opt,name=value,proto3" json:"value,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TenantId      string                 `protobuf:"bytes,7,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_spp_v1_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_spp_v1_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_spp_v1_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *Metric) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Metric) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Metric) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *Metric) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Metric) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

var File_spp_v1_metrics_proto protoreflect.FileDescriptor

const file_spp_v1_metrics_proto_rawDesc = "" +
	"\n" +
	"\x14spp/v1/metrics.proto\x12\x06spp.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"7\n" +
	"\vMetricBatch\x12(\n" +
	"\ametrics\x18\x01 \x03(\v2\x0e.spp.v1.MetricR\ametrics\"\xc9\x02\n" +
	"\x06Metric\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vmetric_name\x18\x03 \x01(\tR\n" +
	"metricName\x12\x1f\n" +
	"\vmetric_type\x18\x04 \x01(\tR\n" +
	"metricType\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x01R\x05value\x122\n" +
	"\x06labels\x18\x06 \x03(\v2\x1a.spp.v1.Metric.LabelsEntryR\x06labels\x12\x1b\n" +
	"\ttenant_id\x18\a \x01(\tR\btenantId\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B/Z-github.com/entropyops/entropyops-v2/pkg/sppv1b\x06proto3"

var (
	file_spp_v1_metrics_proto_rawDescOnce sync.Once
	file_spp_v1_metrics_proto_rawDescData []byte
)

func file_spp_v1_metrics_proto_rawDescGZIP() []byte {
	file_spp_v1_metrics_proto_rawDescOnce.Do(func() {
		file_spp_v1_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spp_v1_metrics_proto_rawDesc), len(file_spp_v1_metrics_proto_rawDesc)))
	})
	return file_spp_v1_metrics_proto_rawDescData
}

var file_spp_v1_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spp_v1_metrics_proto_goTypes = []any{
	(*MetricBatch)(nil),           // 0: spp.v1.MetricBatch
	(*Metric)(nil),                // 1: spp.v1.Metric
	nil,                           // 2: spp.v1.Metric.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_spp_v1_metrics_proto_depIdxs = []int32{
	1, // 0: spp.v1.MetricBatch.metrics:type_name -> spp.v1.Metric
	3, // 1: spp.v1.Metric.timestamp:type_name -> google.protobuf.Timestamp
	2, // 2: spp.v1.Metric.labels:type_name -> spp.v1.Metric.LabelsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_spp_v1_metrics_proto_init() }
func file_spp_v1_metrics_proto_init() {
	if File_spp_v1_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spp_v1_metrics_proto_rawDesc), len(file_spp_v1_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spp_v1_metrics_proto_goTypes,
		DependencyIndexes: file_spp_v1_metrics_proto_depIdxs,
		MessageInfos:      file_spp_v1_metrics_proto_msgTypes,
	}.Build()
	File_spp_v1_metrics_proto = out.File
	file_spp_v1_metrics_proto_goTypes = nil
	file_spp_v1_metrics_proto_depIdxs = nil
}
