// SystemPhysics Protocol v1 — top-level envelope and service definition.
//
// Every AgenticUDP datagram carrying FLAG_PROTOBUF wraps its payload as an
// Envelope. The receiver switches on signal_type / oneof to route data.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: spp/v1/spp.proto

package sppv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalType int32

const (
	SignalType_SIGNAL_TYPE_UNSPECIFIED SignalType = 0
	SignalType_SIGNAL_TYPE_METRICS     SignalType = 1
	SignalType_SIGNAL_TYPE_TRACES      SignalType = 2
	SignalType_SIGNAL_TYPE_LOGS        SignalType = 3
	SignalType_SIGNAL_TYPE_FINGERPRINT SignalType = 4
	SignalType_SIGNAL_TYPE_CONFIG      SignalType = 5
	SignalType_SIGNAL_TYPE_COMMAND     SignalType = 6
)

// Enum value maps for SignalType.
var (
	SignalType_name = map[int32]string{
		0: "SIGNAL_TYPE_UNSPECIFIED",
		1: "SIGNAL_TYPE_METRICS",
		2: "SIGNAL_TYPE_TRACES",
		3: "SIGNAL_TYPE_LOGS",
		4: "SIGNAL_TYPE_FINGERPRINT",
		5: "SIGNAL_TYPE_CONFIG",
		6: "SIGNAL_TYPE_COMMAND",
	}
	SignalType_value = map[string]int32{
		"SIGNAL_TYPE_UNSPECIFIED": 0,
		"SIGNAL_TYPE_METRICS":     1,
		"SIGNAL_TYPE_TRACES":      2,
		"SIGNAL_TYPE_LOGS":        3,
		"SIGNAL_TYPE_FINGERPRINT": 4,
		"SIGNAL_TYPE_CONFIG":      5,
		"SIGNAL_TYPE_COMMAND":     6,
	}
)

func (x SignalType) Enum() *SignalType {
	p := new(SignalType)
	*p = x
	return p
}

func (x SignalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalType) Descriptor() protoreflect.EnumDescriptor {
	return file_spp_v1_spp_proto_enumTypes[0].Descriptor()
}

func (SignalType) Type() protoreflect.EnumType {
	return &file_spp_v1_spp_proto_enumTypes[0]
}

func (x SignalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalType.Descriptor instead.
func (SignalType) EnumDescriptor() ([]byte, []int) {
	return file_spp_v1_spp_proto_rawDescGZIP(), []int{0}
}

// Envelope is the top-level wrapper for every protobuf datagram over
// AgenticUDP. It replaces the JSON {"signal_type","tenant_id","data"}.
type Envelope struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TenantId   string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SignalType SignalType             `protobuf:"varint,2,opt,name=signal_type,json=signalType,proto3,enum=spp.v1.SignalType" json:"signal_type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Metrics
	//	*Envelope_Traces
	//	*Envelope_Logs
	//	*Envelope_Fingerprint
	//	*Envelope_Config
	//	*Envelope_Command
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_spp_v1_spp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_spp_v1_spp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_spp_v1_spp_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Envelope) GetSignalType() SignalType {
	if x != nil {
		return x.SignalType
	}
	return SignalType_SIGNAL_TYPE_UNSPECIFIED
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetMetrics() *MetricBatch {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *Envelope) GetTraces() *TraceBatch {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Traces); ok {
			return x.Traces
		}
	}
	return nil
}

func (x *Envelope) GetLogs() *LogBatch {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Logs); ok {
			return x.Logs
		}
	}
	return nil
}

func (x *Envelope) GetFingerprint() *Fingerprint {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Fingerprint); ok {
			return x.Fingerprint
		}
	}
	return nil
}

func (x *Envelope) GetConfig() *ConfigPush {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *Envelope) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Command); ok {
			return x.Command
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Metrics struct {
	Metrics *MetricBatch `protobuf:"bytes,10,opt,name=metrics,proto3,oneof"`
}

type Envelope_Traces struct {
	Traces *TraceBatch `protobuf:"bytes,11,opt,name=traces,proto3,oneof"`
}

type Envelope_Logs struct {
	Logs *LogBatch `protobuf:"bytes,12,opt,name=logs,proto3,oneof"`
}

type Envelope_Fingerprint struct {
	Fingerprint *Fingerprint `protobuf:"bytes,13,opt,name=fingerprint,proto3,oneof"`
}

type Envelope_Config struct {
	Config *ConfigPush `protobuf:"bytes,14,opt,name=config,proto3,oneof"`
}

type Envelope_Command struct {
	Command *Command `protobuf:"bytes,15,opt,name=command,proto3,oneof"`
}

func (*Envelope_Metrics) isEnvelope_Payload() {}

func (*Envelope_Traces) isEnvelope_Payload() {}

func (*Envelope_Logs) isEnvelope_Payload() {}

func (*Envelope_Fingerprint) isEnvelope_Payload() {}

func (*Envelope_Config) isEnvelope_Payload() {}

func (*Envelope_Command) isEnvelope_Payload() {}

// Command is a server-to-agent directive (restart collector, update config,
// run diagnostic, etc.). Payload is opaque to the protocol layer.
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandType   string                 `protobuf:"bytes,1,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_spp_v1_spp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_spp_v1_spp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_spp_v1_spp_proto_rawDescGZIP(), []int{1}
}

func (x *Command) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

func (x *Command) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Command) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_spp_v1_spp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_spp_v1_spp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_spp_v1_spp_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_spp_v1_spp_proto protoreflect.FileDescriptor

const file_spp_v1_spp_proto_rawDesc = "" +
	"\n" +
	"\x10spp/v1/spp.proto\x12\x06spp.v1\x1a\x14spp/v1/metrics.proto\x1a\x13spp/v1/traces.proto\x1a\x11spp/v1/logs.proto\x1a\x18spp/v1/fingerprint.proto\x1a\x13spp/v1/config.proto\"\x82\x03\n" +
	"\bEnvelope\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x123\n" +
	"\vsignal_type\x18\x02 \x01(\x0e2\x12.spp.v1.SignalTypeR\n" +
	"signalType\x12/\n" +
	"\ametrics\x18\n" +
	" \x01(\v2\x13.spp.v1.MetricBatchH\x00R\ametrics\x12,\n" +
	"\x06traces\x18\v \x01(\v2\x12.spp.v1.TraceBatchH\x00R\x06traces\x12&\n" +
	"\x04logs\x18\f \x01(\v2\x10.spp.v1.LogBatchH\x00R\x04logs\x127\n" +
	"\vfingerprint\x18\r \x01(\v2\x13.spp.v1.FingerprintH\x00R\vfingerprint\x12,\n" +
	"\x06config\x18\x0e \x01(\v2\x12.spp.v1.ConfigPushH\x00R\x06config\x12+\n" +
	"\acommand\x18\x0f \x01(\v2\x0f.spp.v1.CommandH\x00R\acommandB\t\n" +
	"\apayload\"e\n" +
	"\aCommand\x12!\n" +
	"\fcommand_type\x18\x01 \x01(\tR\vcommandType\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"/\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xbe\x01\n" +
	"\n" +
	"SignalType\x12\x1b\n" +
	"\x17SIGNAL_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SIGNAL_TYPE_METRICS\x10\x01\x12\x16\n" +
	"\x12SIGNAL_TYPE_TRACES\x10\x02\x12\x14\n" +
	"\x10SIGNAL_TYPE_LOGS\x10\x03\x12\x1b\n" +
	"\x17SIGNAL_TYPE_FINGERPRINT\x10\x04\x12\x16\n" +
	"\x12SIGNAL_TYPE_CONFIG\x10\x05\x12\x17\n" +
	"\x13SIGNAL_TYPE_COMMAND\x10\x062\xb4\x02\n" +
	"\x14SystemPhysicsService\x12/\n" +
	"\vPushMetrics\x12\x13.spp.v1.MetricBatch\x1a\v.spp.v1.Ack\x12-\n" +
	"\n" +
	"PushTraces\x12\x12.spp.v1.TraceBatch\x1a\v.spp.v1.Ack\x12)\n" +
	"\bPushLogs\x12\x10.spp.v1.LogBatch\x1a\v.spp.v1.Ack\x125\n" +
	"\x11ReportFingerprint\x12\x13.spp.v1.Fingerprint\x1a\v.spp.v1.Ack\x12-\n" +
	"\n" +
	"PushConfig\x12\x12.spp.v1.ConfigPush\x1a\v.spp.v1.Ack\x12+\n" +
	"\vSendCommand\x12\x0f.spp.v1.Command\x1a\v.spp.v1.AckB/Z-github.com/entropyops/entropyops-v2/pkg/sppv1b\x06proto3"

var (
	file_spp_v1_spp_proto_rawDescOnce sync.Once
	file_spp_v1_spp_proto_rawDescData []byte
)

func file_spp_v1_spp_proto_rawDescGZIP() []byte {
	file_spp_v1_spp_proto_rawDescOnce.Do(func() {
		file_spp_v1_spp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spp_v1_spp_proto_rawDesc), len(file_spp_v1_spp_proto_rawDesc)))
	})
	return file_spp_v1_spp_proto_rawDescData
}

var file_spp_v1_spp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spp_v1_spp_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spp_v1_spp_proto_goTypes = []any{
	(SignalType)(0),     // 0: spp.v1.SignalType
	(*Envelope)(nil),    // 1: spp.v1.Envelope
	(*Command)(nil),     // 2: spp.v1.Command
	(*Ack)(nil),         // 3: spp.v1.Ack
	(*MetricBatch)(nil), // 4: spp.v1.MetricBatch
	(*TraceBatch)(nil),  // 5: spp.v1.TraceBatch
	(*LogBatch)(nil),    // 6: spp.v1.LogBatch
	(*Fingerprint)(nil), // 7: spp.v1.Fingerprint
	(*ConfigPush)(nil),  // 8: spp.v1.ConfigPush
}
var file_spp_v1_spp_proto_depIdxs = []int32{
	0,  // 0: spp.v1.Envelope.signal_type:type_name -> spp.v1.SignalType
	4,  // 1: spp.v1.Envelope.metrics:type_name -> spp.v1.MetricBatch
	5,  // 2: spp.v1.Envelope.traces:type_name -> spp.v1.TraceBatch
	6,  // 3: spp.v1.Envelope.logs:type_name -> spp.v1.LogBatch
	7,  // 4: spp.v1.Envelope.fingerprint:type_name -> spp.v1.Fingerprint
	8,  // 5: spp.v1.Envelope.config:type_name -> spp.v1.ConfigPush
	2,  // 6: spp.v1.Envelope.command:type_name -> spp.v1.Command
	4,  // 7: spp.v1.SystemPhysicsService.PushMetrics:input_type -> spp.v1.MetricBatch
	5,  // 8: spp.v1.SystemPhysicsService.PushTraces:input_type -> spp.v1.TraceBatch
	6,  // 9: spp.v1.SystemPhysicsService.PushLogs:input_type -> spp.v1.LogBatch
	7,  // 10: spp.v1.SystemPhysicsService.ReportFingerprint:input_type -> spp.v1.Fingerprint
	8,  // 11: spp.v1.SystemPhysicsService.PushConfig:input_type -> spp.v1.ConfigPush
	2,  // 12: spp.v1.SystemPhysicsService.SendCommand:input_type -> spp.v1.Command
	3,  // 13: spp.v1.SystemPhysicsService.PushMetrics:output_type -> spp.v1.Ack
	3,  // 14: spp.v1.SystemPhysicsService.PushTraces:output_type -> spp.v1.Ack
	3,  // 15: spp.v1.SystemPhysicsService.PushLogs:output_type -> spp.v1.Ack
	3,  // 16: spp.v1.SystemPhysicsService.ReportFingerprint:output_type -> spp.v1.Ack
	3,  // 17: spp.v1.SystemPhysicsService.PushConfig:output_type -> spp.v1.Ack
	3,  // 18: spp.v1.SystemPhysicsService.SendCommand:output_type -> spp.v1.Ack
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_spp_v1_spp_proto_init() }
func file_spp_v1_spp_proto_init() {
	if File_spp_v1_spp_proto != nil {
		return
	}
	file_spp_v1_metrics_proto_init()
	file_spp_v1_traces_proto_init()
	file_spp_v1_logs_proto_init()
	file_spp_v1_fingerprint_proto_init()
	file_spp_v1_config_proto_init()
	file_spp_v1_spp_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Metrics)(nil),
		(*Envelope_Traces)(nil),
		(*Envelope_Logs)(nil),
		(*Envelope_Fingerprint)(nil),
		(*Envelope_Config)(nil),
		(*Envelope_Command)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spp_v1_spp_proto_rawDesc), len(file_spp_v1_spp_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spp_v1_spp_proto_goTypes,
		DependencyIndexes: file_spp_v1_spp_proto_depIdxs,
		EnumInfos:         file_spp_v1_spp_proto_enumTypes,
		MessageInfos:      file_spp_v1_spp_proto_msgTypes,
	}.Build()
	File_spp_v1_spp_proto = out.File
	file_spp_v1_spp_proto_goTypes = nil
	file_spp_v1_spp_proto_depIdxs = nil
}
