// SystemPhysics Protocol v1 — top-level envelope and service definition.
//
// Every AgenticUDP datagram carrying FLAG_PROTOBUF wraps its payload as an
// Envelope. The receiver switches on signal_type / oneof to route data.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: spp/v1/spp.proto

package sppv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SystemPhysicsService_PushMetrics_FullMethodName       = "/spp.v1.SystemPhysicsService/PushMetrics"
	SystemPhysicsService_PushTraces_FullMethodName        = "/spp.v1.SystemPhysicsService/PushTraces"
	SystemPhysicsService_PushLogs_FullMethodName          = "/spp.v1.SystemPhysicsService/PushLogs"
	SystemPhysicsService_ReportFingerprint_FullMethodName = "/spp.v1.SystemPhysicsService/ReportFingerprint"
	SystemPhysicsService_PushConfig_FullMethodName        = "/spp.v1.SystemPhysicsService/PushConfig"
	SystemPhysicsService_SendCommand_FullMethodName       = "/spp.v1.SystemPhysicsService/SendCommand"
)

// SystemPhysicsServiceClient is the client API for SystemPhysicsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SystemPhysicsService defines the RPC surface. Transport is AgenticUDP, not
// HTTP/2, so these are logical operations mapped to Envelope signal_types
// rather than traditional gRPC streams.
type SystemPhysicsServiceClient interface {
	PushMetrics(ctx context.Context, in *MetricBatch, opts ...grpc.CallOption) (*Ack, error)
	PushTraces(ctx context.Context, in *TraceBatch, opts ...grpc.CallOption) (*Ack, error)
	PushLogs(ctx context.Context, in *LogBatch, opts ...grpc.CallOption) (*Ack, error)
	ReportFingerprint(ctx context.Context, in *Fingerprint, opts ...grpc.CallOption) (*Ack, error)
	PushConfig(ctx context.Context, in *ConfigPush, opts ...grpc.CallOption) (*Ack, error)
	SendCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Ack, error)
}

type systemPhysicsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemPhysicsServiceClient(cc grpc.ClientConnInterface) SystemPhysicsServiceClient {
	return &systemPhysicsServiceClient{cc}
}

func (c *systemPhysicsServiceClient) PushMetrics(ctx context.Context, in *MetricBatch, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SystemPhysicsService_PushMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemPhysicsServiceClient) PushTraces(ctx context.Context, in *TraceBatch, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SystemPhysicsService_PushTraces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemPhysicsServiceClient) PushLogs(ctx context.Context, in *LogBatch, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SystemPhysicsService_PushLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemPhysicsServiceClient) ReportFingerprint(ctx context.Context, in *Fingerprint, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SystemPhysicsService_ReportFingerprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemPhysicsServiceClient) PushConfig(ctx context.Context, in *ConfigPush, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SystemPhysicsService_PushConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemPhysicsServiceClient) SendCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, SystemPhysicsService_SendCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemPhysicsServiceServer is the server API for SystemPhysicsService service.
// All implementations must embed UnimplementedSystemPhysicsServiceServer
// for forward compatibility.
//
// SystemPhysicsService defines the RPC surface. Transport is AgenticUDP, not
// HTTP/2, so these are logical operations mapped to Envelope signal_types
// rather than traditional gRPC streams.
type SystemPhysicsServiceServer interface {
	PushMetrics(context.Context, *MetricBatch) (*Ack, error)
	PushTraces(context.Context, *TraceBatch) (*Ack, error)
	PushLogs(context.Context, *LogBatch) (*Ack, error)
	ReportFingerprint(context.Context, *Fingerprint) (*Ack, error)
	PushConfig(context.Context, *ConfigPush) (*Ack, error)
	SendCommand(context.Context, *Command) (*Ack, error)
	mustEmbedUnimplementedSystemPhysicsServiceServer()
}

// UnimplementedSystemPhysicsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemPhysicsServiceServer struct{}

func (UnimplementedSystemPhysicsServiceServer) PushMetrics(context.Context, *MetricBatch) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method PushMetrics not implemented")
}
func (UnimplementedSystemPhysicsServiceServer) PushTraces(context.Context, *TraceBatch) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method PushTraces not implemented")
}
func (UnimplementedSystemPhysicsServiceServer) PushLogs(context.Context, *LogBatch) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method PushLogs not implemented")
}
func (UnimplementedSystemPhysicsServiceServer) ReportFingerprint(context.Context, *Fingerprint) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportFingerprint not implemented")
}
func (UnimplementedSystemPhysicsServiceServer) PushConfig(context.Context, *ConfigPush) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method PushConfig not implemented")
}
func (UnimplementedSystemPhysicsServiceServer) SendCommand(context.Context, *Command) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedSystemPhysicsServiceServer) mustEmbedUnimplementedSystemPhysicsServiceServer() {}
func (UnimplementedSystemPhysicsServiceServer) testEmbeddedByValue()                              {}

// UnsafeSystemPhysicsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemPhysicsServiceServer will
// result in compilation errors.
type UnsafeSystemPhysicsServiceServer interface {
	mustEmbedUnimplementedSystemPhysicsServiceServer()
}

func RegisterSystemPhysicsServiceServer(s grpc.ServiceRegistrar, srv SystemPhysicsServiceServer) {
	// If the following call panics, it indicates UnimplementedSystemPhysicsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemPhysicsService_ServiceDesc, srv)
}

func _SystemPhysicsService_PushMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemPhysicsServiceServer).PushMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemPhysicsService_PushMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemPhysicsServiceServer).PushMetrics(ctx, req.(*MetricBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemPhysicsService_PushTraces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemPhysicsServiceServer).PushTraces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemPhysicsService_PushTraces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemPhysicsServiceServer).PushTraces(ctx, req.(*TraceBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemPhysicsService_PushLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemPhysicsServiceServer).PushLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemPhysicsService_PushLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemPhysicsServiceServer).PushLogs(ctx, req.(*LogBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemPhysicsService_ReportFingerprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Fingerprint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemPhysicsServiceServer).ReportFingerprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemPhysicsService_ReportFingerprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemPhysicsServiceServer).ReportFingerprint(ctx, req.(*Fingerprint))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemPhysicsService_PushConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigPush)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemPhysicsServiceServer).PushConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemPhysicsService_PushConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemPhysicsServiceServer).PushConfig(ctx, req.(*ConfigPush))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemPhysicsService_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemPhysicsServiceServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemPhysicsService_SendCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemPhysicsServiceServer).SendCommand(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemPhysicsService_ServiceDesc is the grpc.ServiceDesc for SystemPhysicsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemPhysicsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spp.v1.SystemPhysicsService",
	HandlerType: (*SystemPhysicsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushMetrics",
			Handler:    _SystemPhysicsService_PushMetrics_Handler,
		},
		{
			MethodName: "PushTraces",
			Handler:    _SystemPhysicsService_PushTraces_Handler,
		},
		{
			MethodName: "PushLogs",
			Handler:    _SystemPhysicsService_PushLogs_Handler,
		},
		{
			MethodName: "ReportFingerprint",
			Handler:    _SystemPhysicsService_ReportFingerprint_Handler,
		},
		{
			MethodName: "PushConfig",
			Handler:    _SystemPhysicsService_PushConfig_Handler,
		},
		{
			MethodName: "SendCommand",
			Handler:    _SystemPhysicsService_SendCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spp/v1/spp.proto",
}
