// SystemPhysics Protocol v1 — trace/span messages.
// Maps 1:1 to storage.Trace in the Go codebase.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: spp/v1/traces.proto

package sppv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TraceBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spans         []*Span                `protobuf:"bytes,1,rep,name=spans,proto3" json:"spans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceBatch) Reset() {
	*x = TraceBatch{}
	mi := &file_spp_v1_traces_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceBatch) ProtoMessage() {}

func (x *TraceBatch) ProtoReflect() protoreflect.Message {
	mi := &file_spp_v1_traces_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceBatch.ProtoReflect.Descriptor instead.
func (*TraceBatch) Descriptor() ([]byte, []int) {
	return file_spp_v1_traces_proto_rawDescGZIP(), []int{0}
}

func (x *TraceBatch) GetSpans() []*Span {
	if x != nil {
		return x.Spans
	}
	return nil
}

type Span struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        string                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	ParentSpanId  string                 `protobuf:"bytes,3,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	OperationName string                 `protobuf:"bytes,5,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	DurationUs    int64                  `protobuf:"varint,8,opt,name=duration_us,json=durationUs,proto3" json:"duration_us,omitempty"`
	StatusCode    string                 `protobuf:"bytes,9,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	SpanKind      string                 `protobuf:"bytes,10,opt,name=span_kind,json=spanKind,proto3" json:"span_kind,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,11,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TenantId      string                 `protobuf:"bytes,12,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_spp_v1_traces_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_spp_v1_traces_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_spp_v1_traces_proto_rawDescGZIP(), []int{1}
}

func (x *Span) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Span) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *Span) GetParentSpanId() string {
	if x != nil {
		return x.ParentSpanId
	}
	return ""
}

func (x *Span) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Span) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *Span) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Span) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Span) GetDurationUs() int64 {
	if x != nil {
		return x.DurationUs
	}
	return 0
}

func (x *Span) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *Span) GetSpanKind() string {
	if x != nil {
		return x.SpanKind
	}
	return ""
}

func (x *Span) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Span) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

var File_spp_v1_traces_proto protoreflect.FileDescriptor

const file_spp_v1_traces_proto_rawDesc = "" +
	"\n" +
	"\x13spp/v1/traces.proto\x12\x06spp.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"0\n" +
	"\n" +
	"TraceBatch\x12\"\n" +
	"\x05spans\x18\x01 \x03(\v2\f.spp.v1.SpanR\x05spans\"\x95\x04\n" +
	"\x04Span\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x12$\n" +
	"\x0eparent_span_id\x18\x03 \x01(\tR\fparentSpanId\x12!\n" +
	"\fservice_name\x18\x04 \x01(\tR\vserviceName\x12%\n" +
	"\x0eoperation_name\x18\x05 \x01(\tR\roperationName\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1f\n" +
	"\vduration_us\x18\b \x01(\x03R\n" +
	"durationUs\x12\x1f\n" +
	"\vstatus_code\x18\t \x01(\tR\n" +
	"statusCode\x12\x1b\n" +
	"\tspan_kind\x18\n" +
	" \x01(\tR\bspanKind\x12<\n" +
	"\n" +
	"attributes\x18\v \x03(\v2\x1c.spp.v1.Span.AttributesEntryR\n" +
	"attributes\x12\x1b\n" +
	"\ttenant_id\x18\f \x01(\tR\btenantId\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B/Z-github.com/entropyops/entropyops-v2/pkg/sppv1b\x06proto3"

var (
	file_spp_v1_traces_proto_rawDescOnce sync.Once
	file_spp_v1_traces_proto_rawDescData []byte
)

func file_spp_v1_traces_proto_rawDescGZIP() []byte {
	file_spp_v1_traces_proto_rawDescOnce.Do(func() {
		file_spp_v1_traces_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spp_v1_traces_proto_rawDesc), len(file_spp_v1_traces_proto_rawDesc)))
	})
	return file_spp_v1_traces_proto_rawDescData
}

var file_spp_v1_traces_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spp_v1_traces_proto_goTypes = []any{
	(*TraceBatch)(nil),            // 0: spp.v1.TraceBatch
	(*Span)(nil),                  // 1: spp.v1.Span
	nil,                           // 2: spp.v1.Span.AttributesEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_spp_v1_traces_proto_depIdxs = []int32{
	1, // 0: spp.v1.TraceBatch.spans:type_name -> spp.v1.Span
	3, // 1: spp.v1.Span.start_time:type_name -> google.protobuf.Timestamp
	3, // 2: spp.v1.Span.end_time:type_name -> google.protobuf.Timestamp
	2, // 3: spp.v1.Span.attributes:type_name -> spp.v1.Span.AttributesEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_spp_v1_traces_proto_init() }
func file_spp_v1_traces_proto_init() {
	if File_spp_v1_traces_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spp_v1_traces_proto_rawDesc), len(file_spp_v1_traces_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spp_v1_traces_proto_goTypes,
		DependencyIndexes: file_spp_v1_traces_proto_depIdxs,
		MessageInfos:      file_spp_v1_traces_proto_msgTypes,
	}.Build()
	File_spp_v1_traces_proto = out.File
	file_spp_v1_traces_proto_goTypes = nil
	file_spp_v1_traces_proto_depIdxs = nil
}
